-- 工资结构表
CREATE TABLE IF NOT EXISTS salary_structure (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  sort_order INT NOT NULL DEFAULT 0,
  component  VARCHAR(100) NOT NULL DEFAULT '' COMMENT '薪资构成',
  amount     VARCHAR(100) NOT NULL DEFAULT '' COMMENT '薪资额度',
  remark     VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工资结构表';
